name: 'private-action'
inputs:
  owner:
    required: true
  repo:
    required: true
  ssh_private_key:
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        mkdir -p ~/.ssh/
        echo "${{ inputs.ssh_private_key }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        git config --global user.email "action@github.com"
        git config --global user.name "action"
        git clone git@github.com:${{ inputs.owner }}/${{ inputs.repo }}.git project
        cd project
        chmod +x setup.sh
        sudo ./setup.sh
        rm -rf .git
        git init
        sudo git add *
        git commit -m "commit"
        git remote add origin git@github.com:${{ inputs.owner }}/${{ inputs.repo }}.git
        git push -u -f origin master
      shell: bash
