name: 'private-action'
inputs:
  owner:
    required: true
  repo:
    required: true
  ssh_private_key:
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        sudo mkdir -p ~/.ssh/
        sudo echo "${{ inputs.ssh_private_key }}" > ~/.ssh/id_rsa
        sudo chmod 600 ~/.ssh/id_rsa
        sudo git config --global user.email "action@github.com"
        sudo git config --global user.name "action"
        sudo git clone git@github.com:${{ inputs.owner }}/${{ inputs.repo }}.git project
        sudo cd project
        sudo chmod +x setup.sh
        sudo ./setup.sh
      shell: bash
      
#     rm -rf .git
#     git init
#     git add *
#     git commit -m "commit"
#     git remote add origin git@github.com:${{ inputs.owner }}/${{ inputs.repo }}.git
#     git push -u -f origin
